name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-26 
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: make test